### ISSUE TITLE
Fails to parse valid yaml

### ISSUE THREAD

**Issue by rayjlinden** [abiosoft/caddy-yaml#1]
I wanted to try out this adapter.  I used a little utility to convert the json to yaml.  Tried it out and got this error:
```
{"level":"info","ts":1611044403.9202049,"msg":"using provided configuration","config_file":"/config.yml","config_adapter":"yaml"}
run: adapting config using yaml: template: yaml:464: bad character U+0022 '"'
```

I know it is valid yaml.  More odd is there is no double-quote character on line 464

I know this is not much info to go on.  Any suggestions on how I can figure out what is wrong?

**Comment by rayjlinden** [comment]
The one thing I'm wondering about is I have things like:
```
              - handler: headers
                response:
                  set:
                    X-Frame-Options:
                    - SAMEORIGIN
              - handler: reverse_proxy
                headers:
                  request:
                    set:
                      Host:
                      - "{http.request.host}"
                      X-Forwarded-For:
                      - "{http.request.remote}"
                      X-Real-Ip:
                      - "{http.request.remote}"
```

I wonder if the use of these header values is conflicting with your x- processing...
