### ISSUE TITLE
undefined variable `$affinity` when running with simple yaml config

### ISSUE THREAD

**Issue by melink14** [abiosoft/caddy-yaml#2]
Full error message:
`run: adapting config using yaml: template: yaml:3: undefined variable "$affinity"`

Config which does not contain that variable:
```
apps:
  layer4:
    servers:
      mdath:
        listen:
          - "127.0.0.1:443"
        routes:
          - match:
            - tls:
              sni:
                - "*.host.com"
            handle:
              - handler: "proxy"
                upstreams:
                  - dial:
                    - "localhost:4433"
```

Not sure what could be wrong given the simplicity and lack of error context but posting here in case someone has the answer!
