### ISSUE TITLE
Error converting YAML to JSON

### ISSUE THREAD

**Issue by mattfysh** [abiosoft/caddy-yaml#3]
Getting the following error:

```
run: adapting config using yaml: error converting YAML to JSON: yaml: line 14: did not find expected node content
```

With the following config yaml:

```yaml
logging:
  logs:
    default:
      level: DEBUG
apps:
  layer4:
    servers:
      srv0:
        listen: [:80]
        routes:
          - match:
              - http: []
            handle:
              - handler: proxy
                upstreams:
                  - dial:
                    - 127.0.0.1:8080
```

When I convert the YAML to JSON manually, the JSON config file runs with no issue
